# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

addons:
  apt:
    packages:
      - libwebp-dev
      - libpoppler-cpp-dev
      - valgrind
      - gcc-4.9
      - g++-4.9
